FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g prisma
RUN npm install bcrypt

COPY . .

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate dev --name init && npm run dev --host 0.0.0.0"]
