version: '3.8'

services:

  postgres:
    image: postgres
    container_name: db_member
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: e-koin
    ports:
      - "5432:5432"
    volumes:
      - data:/data/postgres
  app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - DATABASE_URL=postgresql://root:root@db_member:5432/e-koin?schema=public
      - JWT_SECRET_KEY=khanazulfanaimam
      - IMAGEKIT_PUBLIC_KEY = public_zvbKR1yVvHfTs10j2TnNH/t9rNU=
      - IMAGEKIT_PRIVATE_KEY = private_cnF5s+oz55nNIPEwVLf0mZrI4z8=
      - IMAGEKIT_URL_ENDPOINT = https://ik.imagekit.io/8zmr0xxik
    restart: always
    ports:
      - "9898:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    container_name: be_member
volumes: 
 data: {}
